#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
iview cli
"""

import click
from click_support import PATH
import iview


@click.command()
@click.argument("paths", type=PATH, nargs=-1)
def main(paths):
    """
    iview1 - a digital photo viewer

    \b
    iview1 displays the image specified by PATHS.
    PATHS is a list of image paths or a directory containing images.

    iview1 allows you to step forward or backward though all the images
    and/or image directories specified in the arguments.

    \b
    Press
      <SPACE>     to go to the next image.
      <BACKSPACE> to go to the previous image.
      <DELETE>    to delete the current image.
      <ESCAPE>    to exit.
    """

    if not paths:
        context = click.get_current_context()
        click.echo(context.get_help())
    else:
        iview.main(paths)


if __name__ == "__main__":
    main()
