#!/usr/bin/env python

"""
iview cli
"""

from pathlib import Path
from type_ext import List, FilePath
import util
import iview
import typer


def main(
    paths: List[Path],  # List[FilePath],
    recursive: bool = typer.Option(
        False,
        "--recursive",
        "-r",
        help="Traverse subdirectories of directories included in PATHS",
    ),
) -> None:
    """
    {app} - a digital photo viewer

    \b
    {app} allows you to step forward or backward though all the images
    and/or image directories specified in the arguments.

    {app} displays the image specified by PATHS.
    PATHS is a list of image paths or a directory containing images.

    \b
    Press
      <SPACE>     to go to the next image.
      <BACKSPACE> to go to the previous image.
      <DELETE>    to delete the current image.
      <ESCAPE>    to exit.
    """

    iview.App(paths, subdirectories=recursive).run()


if __name__ == "__main__":
    util.update_docstring(main, app=Path(__file__).name)
    typer.run(main)
